name: rnaseqsamplesize-1.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r::r-base=3.5.1
  - bioconda::bioconductor-rnaseqsamplesize=1.12.0
  - conda-forge::libgfortran=3.0.0
  - pip
  - pip:
    - dync
    - attachi
